in:
  type: google_spreadsheets
  auth_method: authorized_user
  json_keyfile: "/tmp/google_spreadsheets_output_option/json_key_exCWRThcAEI.json"
  spreadsheets_url: https://docs.google.com/spreadsheets/d/1OZL-u-NqKBfvz1BOblXpshhsKY0x1NYfA7ACTd1eUnU/edit?gid=0#gid=0
  worksheet_title: "'シート1'"
  start_row: 2
  start_column: 1
  default_timezone: Asia/Tokyo
  null_string: ''
  default_typecast: strict
  columns:
  - name: workerID
    type: long
  - name: value
    type: timestamp
    format: "%Y/%m/%d %H:%M:%S"
out:
  type: stdout
